global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  # Internal Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Our Worker Orchestrator Metrics
  - job_name: 'orchestrator-metrics'
    metrics_path: '/metrics'
    static_configs:
      # Points to the docker-compose orchestrator service network alias
      - targets: ['orchestrator:8080']
